# PyTorch Tensor Basic Useage

* Create Tensor
* Indexing, Joining, Slicing
* Initialization
* Math Operations

## 1. Create Tensor

### 1-1 Random Numbers

In [15]:
import torch
# torch.rand(size) : 0~1 미만 사이의 값을 갖는 tensor를 생성
x = torch.rand(2,3)
x

tensor([[ 0.1106,  0.2431,  0.6100],
        [ 0.3003,  0.9838,  0.5618]])

In [16]:
#torch.randn(size) : 0을 평균으로 갖는 normal distribution 값을 갖는 tensor를 생성
x=torch.randn(2,3)
x

tensor([[ 1.2367,  0.7469, -0.2597],
        [ 2.3327,  0.3218,  0.6509]])

In [17]:
# torch.randperm(n) : 0 ~ n-1 까지 random 정수 무작위 배열
x = torch.randperm(5)
x

tensor([ 2,  0,  1,  4,  3])

### 1-2 Zeros, Ones, Range

In [18]:
x = torch.zeros(2,3)
x

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [19]:
x = torch.ones(2,3)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [20]:
x = torch.range(0,3, step=0.5)
x

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000])

### 1-3 Tensor Data Type

In [21]:
x = torch.FloatTensor(2,3)
x

tensor(1.00000e-19 *
       [[ 0.0000, -0.0000,  0.0000],
        [ 1.0845,  0.0000,  0.0000]])

In [22]:
#torch.FloatTensor(size or list): 사이즈 또는 리스트 형태의 실제 텐서 값을 표시
x = torch.FloatTensor([2,3])
x

tensor([ 2.,  3.])

In [23]:
x = torch.FloatTensor([[2,3],[3,5]])
x

tensor([[ 2.,  3.],
        [ 3.,  5.]])

In [24]:
x = torch.FloatTensor(2,3)
x= x.type_as(torch.IntTensor())
x

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.1475e+09,  0.0000e+00,  0.0000e+00]], dtype=torch.int32)

### 1-4 Numpy to Tensor, Tensor to Numpy

In [25]:
import numpy as np

x1 = np.ndarray(shape=(2,3), dtype=int, buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)
x2

tensor([[ 1,  2,  3],
        [ 4,  5,  6]])

In [26]:
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 1-5 Tensor on GPU & CPU

In [27]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [28]:
x_gpu= x.cuda()
x_gpu

RuntimeError: torch.cuda.FloatTensor is not enabled.

In [29]:
x_cpu = x_gpu.cpu()
x_cpu

NameError: name 'x_gpu' is not defined

## 2. Indexing, Joining, Slicing, Reshaping

### 2-1 Indexing

In [30]:
# torch.index_select(input, dim, index)
x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,2]))
x, out

(tensor([[ 0.7779,  0.9854,  0.5303],
         [ 0.9620,  0.6227,  0.7694],
         [ 0.9260,  0.0400,  0.4925],
         [ 0.1519,  0.7610,  0.1049]]), tensor([[ 0.7779,  0.9854,  0.5303],
         [ 0.9260,  0.0400,  0.4925]]))

In [31]:
x[:,0]

tensor([ 0.7779,  0.9620,  0.9260,  0.1519])

In [32]:
x[0,:]

tensor([ 0.7779,  0.9854,  0.5303])

In [33]:
x[0:2,0:1]

tensor([[ 0.7779],
        [ 0.9620]])

In [34]:
# torch.masked_select(input, mask)
x=torch.rand(2,3)
mask = torch.ByteTensor([[0,1,1],[0,1,0]])
out = torch.masked_select(x,mask)
x, mask, out

(tensor([[ 0.9105,  0.4859,  0.5874],
         [ 0.2995,  0.6916,  0.2644]]), tensor([[ 0,  1,  1],
         [ 0,  1,  0]], dtype=torch.uint8), tensor([ 0.4859,  0.5874,  0.6916]))

### 2-2 Joining

In [35]:
x=torch.IntTensor([[1,2,3],[4,5,6]])
y=torch.IntTensor([[-1,-2,-3],[-4,-5,-6]])
z1=torch.cat([x,y], dim=0)
z2=torch.cat([x,y], dim=1)
x,y,z1,z2

(tensor([[ 1,  2,  3],
         [ 4,  5,  6]], dtype=torch.int32), tensor([[-1, -2, -3],
         [-4, -5, -6]], dtype=torch.int32), tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [-1, -2, -3],
         [-4, -5, -6]], dtype=torch.int32), tensor([[ 1,  2,  3, -1, -2, -3],
         [ 4,  5,  6, -4, -5, -6]], dtype=torch.int32))

### 2-3 Slicing

In [44]:
# torch.chunk(input, chunks, dim=0 or 1)
x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3=torch.chunk(z1,3,dim=1)
z1, x_1, x_2 ,y_1, y_2, y_3

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [-1, -2, -3],
         [-4, -5, -6]], dtype=torch.int32), tensor([[ 1,  2,  3],
         [ 4,  5,  6]], dtype=torch.int32), tensor([[-1, -2, -3],
         [-4, -5, -6]], dtype=torch.int32), tensor([[ 1],
         [ 4],
         [-1],
         [-4]], dtype=torch.int32), tensor([[ 2],
         [ 5],
         [-2],
         [-5]], dtype=torch.int32), tensor([[ 3],
         [ 6],
         [-3],
         [-6]], dtype=torch.int32))

In [48]:
x_1= torch.split(z1,2,dim=0)
y_1=torch.split(z1,2,dim=1)
z1, x_1,y_1

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [-1, -2, -3],
         [-4, -5, -6]], dtype=torch.int32), (tensor([[ 1,  2,  3],
          [ 4,  5,  6]], dtype=torch.int32), tensor([[-1, -2, -3],
          [-4, -5, -6]], dtype=torch.int32)), (tensor([[ 1,  2],
          [ 4,  5],
          [-1, -2],
          [-4, -5]], dtype=torch.int32), tensor([[ 3],
          [ 6],
          [-3],
          [-6]], dtype=torch.int32)))

In [56]:
#torch.squeeze()와 torch.unsqueeze()는 서로 상반된 역할을 합니다. 
#‘쥐어짜다’라는 느낌에서 어떤 역할을 할지 감이 오지 않으신가요? 맞습니다. 
#torch.squeeze()를 할경우 차원의 사이즈가 ‘1’인 차원을 없애주며, 
#반대로 torch.unsqueeze()는 차원의 사이즈가 ‘1’인 차원을 원하는 차원에 생성을 해줍니다.
x1=torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)
x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [62]:
x1=torch.FloatTensor(10,1,3)
x2=torch.unsqueeze(x1, dim=3)
x2.size()

torch.Size([10, 1, 3, 1])

## 3.Initialization

In [63]:
import torch.nn.init as init

In [68]:
x1 = init.uniform(torch.FloatTensor(3,4), a=0, b=2)
x2= init.normal(torch.FloatTensor(3,4), std=0.2)
x3 = init.constant(torch.FloatTensor(3,4), 3.1415)

x1,x2,x3

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  This is separate from the ipykernel package so we can avoid doing imports until


(tensor([[ 1.4800,  0.6521,  1.6379,  1.1624],
         [ 0.7764,  0.1513,  0.1985,  0.9169],
         [ 1.4594,  1.8564,  0.1031,  0.0738]]),
 tensor([[ 0.0351,  0.2481, -0.1464, -0.0681],
         [-0.2935, -0.0119, -0.0848,  0.0514],
         [ 0.0039,  0.0834, -0.3169, -0.3104]]),
 tensor([[ 3.1415,  3.1415,  3.1415,  3.1415],
         [ 3.1415,  3.1415,  3.1415,  3.1415],
         [ 3.1415,  3.1415,  3.1415,  3.1415]]))

## 4. Math Operation

### 4-1 Arithmetic operations

In [71]:
# torch.add(tensor1, tensor2)
x1= torch.FloatTensor([[1,1,1],[1,1,1]])
x2=torch.FloatTensor([[1,1,1],[1,1,1]])
add = torch.add(x1,x2)
x1, x2,add,x1+x2,x1-x2

(tensor([[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]), tensor([[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]), tensor([[ 2.,  2.,  2.],
         [ 2.,  2.,  2.]]), tensor([[ 2.,  2.,  2.],
         [ 2.,  2.,  2.]]), tensor([[ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]))

In [74]:
# torch.add() broadcasting
x1 = torch.FloatTensor([[1,1,1],[1,1,1]])
add = torch.add(x1, 10)
add, x1+10

(tensor([[ 11.,  11.,  11.],
         [ 11.,  11.,  11.]]), tensor([[ 11.,  11.,  11.],
         [ 11.,  11.,  11.]]))

In [76]:
x1=torch.FloatTensor([[2,2,2],[2,2,2]])
x2=torch.FloatTensor([[3,3,3],[3,3,3]])
x3=torch.mul(x1,x2)
x3, x1 * 3

(tensor([[ 6.,  6.,  6.],
         [ 6.,  6.,  6.]]), tensor([[ 6.,  6.,  6.],
         [ 6.,  6.,  6.]]))

In [78]:
x1=torch.FloatTensor([[2,2,2],[2,2,2]])
x2=torch.FloatTensor([[2,2,2],[2,2,2]])
x3 = torch.div(x1, x2)
x3, x1/2

(tensor([[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]), tensor([[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]))

### 4-2 Other Math Operations

In [83]:
# torch.pow(tensor, exponent)
x1 = torch.FloatTensor([[2,2,2],[3,3,3]])
x2 = torch.pow(x1, 2)
x2, x1**2

(tensor([[ 4.,  4.,  4.],
         [ 9.,  9.,  9.]]), tensor([[ 4.,  4.,  4.],
         [ 9.,  9.,  9.]]))

In [84]:
x1 = torch.FloatTensor([[2,2,2],[3,3,3]])
x2 = torch.exp(x1)
x2

tensor([[  7.3891,   7.3891,   7.3891],
        [ 20.0855,  20.0855,  20.0855]])

In [85]:
x1 = torch.FloatTensor([[2,2,2],[3,3,3]])
x2 = torch.log(x1)
x2

tensor([[ 0.6931,  0.6931,  0.6931],
        [ 1.0986,  1.0986,  1.0986]])

### 4-3 Matrix operations

In [92]:
#torch.mm(tensor, tensor) tensor matrix muliplication
x1= torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,3)
x3=torch.mm(x1, x2)
x3

tensor(1.00000e-35 *
       [[ 0.0000, -1.6833,  0.0000],
        [ 0.0000, -1.6833,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [95]:
#Performs a batch matrix-matrix product of matrices stored in batch1 and batch2.
#batch1 and batch2 must be 3-D tensors each containing the same number of matrices.
#If batch1 is a (b×n×m) tensor, batch2 is a (b×m×p) tensor, out will be a (b×n×p) tensor.
x1= torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,3)
x3=torch.bmm(x1, x2)
x3.size()


torch.Size([10, 3, 3])

In [98]:
# torch.dot(1dim tensor, 1dim tensor) 벡터의 내적
x1=torch.FloatTensor([2,2,2])
x2=torch.FloatTensor([3,3,3])
x3=torch.dot(x1, x2)
x3

tensor(18.)

In [102]:
#torch.t(matrix) : transposed matrix
x1 = torch.IntTensor(3,4)
x1, x1.t()

(tensor([[ 0.0000e+00, -1.8790e+09,  0.0000e+00, -1.8790e+09],
         [ 6.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.int32),
 tensor([[ 0.0000e+00,  6.0000e+00,  0.0000e+00],
         [-1.8790e+09,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-1.8790e+09,  0.0000e+00,  0.0000e+00]], dtype=torch.int32))

In [110]:
x1 = torch.FloatTensor(10,2,3)
x1.size(), torch.transpose(x1, 1,2).size(), x1.transpose(0,1).size()

(torch.Size([10, 2, 3]), torch.Size([10, 3, 2]), torch.Size([2, 10, 3]))