# Variable & Automatic Gradient Calculation

* Tensor vs Variable
* Graph and Gradient

## 1. Import Required Libraries

In [32]:
import torch
from torch.autograd import Variable

## 2. Tensor vs Variable

### 2-1 Declaration

In [33]:
x_tensor = torch.FloatTensor(3,4)
x_tensor

tensor(1.00000e-10 *
       [[ 0.0000, -4.6566,  0.0000, -4.6566],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [34]:
x_variable = Variable(x_tensor)
x_variable

tensor(1.00000e-10 *
       [[ 0.0000, -4.6566,  0.0000, -4.6566],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

### 2-2 Variable of Variable

In [35]:
x_variable.data

tensor(1.00000e-10 *
       [[ 0.0000, -4.6566,  0.0000, -4.6566],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])

In [36]:
print(x_variable.grad)

None


In [37]:
x_variable.requires_grad

False

In [38]:
x_variable = Variable(x_tensor, requires_grad=True)
x_variable.requires_grad

True

### 2-3 Graph & Variables

In [59]:
# create graph
x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y= x**2 + 4*x
z = 2*y+3

x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [60]:
gradient = torch.Tensor(3,4)
z.backward(gradient)
print(x.grad)
z.grad, y.grad

tensor([[ 0.0000e+00, -3.7253e-09, -1.6527e+07, -1.6004e+01],
        [ 3.3631e-44,  7.8473e-44,  1.4153e-30,  1.1210e-44],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  2.2041e-39]])


(None, None)

In [64]:
x=Variable(torch.ones(3), requires_grad=True)
y=x**2
z=y.sum()
z.backward()

In [67]:
print(x.grad)

tensor([ 2.,  2.,  2.])


In [71]:
x=Variable(torch.ones(3), requires_grad=True)
y=x**2
z=y*2
gradient = torch.Tensor([0.1,1,10])
z.backward(gradient)
x.grad

tensor([  0.4000,   4.0000,  40.0000])