In [4]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import  torch.nn.init as init
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
x = init.uniform(torch.FloatTensor(1000,1), -10,10)
y = init.uniform(torch.FloatTensor(1000,1), -20,20)
z = x**2 + y**2


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  


In [10]:
input_data=Variable(torch.cat([x,y], dim=1))

model = nn.Sequential(
                nn.Linear(2,20),
                nn.ReLU(),
                nn.Linear(20,20),
                nn.ReLU(),
                nn.Linear(20,5),
                nn.ReLU(),
                nn.Linear(5,5),
                nn.ReLU(),
                nn.Linear(5,1),
)

In [13]:
criterion = nn.L1Loss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [16]:
for i in range(5000):
    optimizer.zero_grad()
    y_pred = model(input_data)
    loss = criterion(y_pred, Variable(z))
    loss.backward()
    optimizer.step()
    
    if i % 50 == 0:
        print(i, loss)
        
    
    

0 tensor(84.2508)
50 tensor(55.6053)
100 tensor(64.8638)
150 tensor(109.7617)
200 tensor(88.5479)
250 tensor(67.3678)
300 tensor(77.1365)
350 tensor(68.4747)
400 tensor(44.0355)
450 tensor(69.5647)
500 tensor(59.3707)
550 tensor(42.5529)
600 tensor(50.2187)
650 tensor(66.3177)
700 tensor(119.0559)
750 tensor(46.3037)
800 tensor(48.2028)
850 tensor(45.4346)
900 tensor(41.2463)
950 tensor(62.4149)
1000 tensor(36.0279)
1050 tensor(43.8875)
1100 tensor(73.2444)
1150 tensor(33.3010)
1200 tensor(38.0819)
1250 tensor(58.8421)
1300 tensor(60.1150)
1350 tensor(70.3454)
1400 tensor(56.2581)
1450 tensor(56.6887)
1500 tensor(32.6212)
1550 tensor(46.0170)
1600 tensor(45.0765)
1650 tensor(32.4599)
1700 tensor(106.2813)
1750 tensor(44.8678)
1800 tensor(35.5626)
1850 tensor(54.1984)
1900 tensor(100.3758)
1950 tensor(47.0100)
2000 tensor(57.0554)
2050 tensor(65.9233)
2100 tensor(41.3398)
2150 tensor(48.5592)
2200 tensor(47.8706)
2250 tensor(63.1410)
2300 tensor(62.4391)
2350 tensor(63.1961)
2400 tensor

In [17]:
param_list = list(model.parameters())
print(param_list)

[Parameter containing:
tensor([[-0.9924, -0.6142],
        [-0.1032, -1.1577],
        [-0.5743,  0.2177],
        [ 0.1048,  0.9133],
        [-0.0834,  0.6318],
        [ 0.5316, -0.2774],
        [ 0.8312, -0.7206],
        [-0.0513,  0.0055],
        [-0.0480, -0.0020],
        [-0.4809, -0.3883],
        [-0.0956,  1.0601],
        [ 0.0505, -0.5609],
        [-0.2392, -0.7819],
        [-0.0560, -1.2147],
        [-1.2029,  0.2927],
        [ 0.2005, -0.9345],
        [ 1.2604,  0.7387],
        [-0.2158,  1.6062],
        [ 0.4454, -0.3237],
        [-0.4149,  0.1771]]), Parameter containing:
tensor([-6.6181, -8.3991, -2.9767, -7.1228, -5.3685, -1.8952, -6.0033,
        -0.6026, -0.5173, -4.0906, -9.1687, -4.2959, -3.1481, -8.9991,
        -4.1872, -6.6725, -6.7532, -8.1767, -2.8575, -2.3972]), Parameter containing:
tensor([[-0.5857,  0.4372, -0.6405, -0.2844, -0.3397,  0.4484,  0.3558,
         -0.1152, -0.3878, -0.1847,  0.1295,  0.3434, -0.0056,  0.5213,
         -0.5938,  0.